version: '3'

services:
  backend:
    image: strapi/strapi
    container_name: "nextjs-strapi-backend-${ENV}"
    build:
      context: .
    depends_on:
      - db
    environment:
      ENV: "${ENV}"
      DATABASE_CLIENT: "${DATABASE_CLIENT}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "1337:1337"
    restart: on-failure
    volumes:
      - ./app:/srv/app

  db:
    container_name: "nextjs-strapi-mysql-${ENV}"
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "${DATABASE_CLIENT}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ../data:/var/lib/mysql
    restart: unless-stopped
